services:

  geth:
    image: ${GO_CLIENT_TOOL}
    command: /root/init.sh
    volumes:
      - ./init.sh:/root/init.sh
    ports:
      - "8545:8545"
      - "30303:30303"
    networks:
      - local

networks:
  local:
    name: ${NETWORK_NAME}